[[section-building-block-view]]


== Building Block View
This section will show the static decomposition of the system into building blocks as well as their dependencies. We will zoom into black boxes of the different levels to show their components. 

For reference, we are going to use the scope and context diagram that has been described in the third section of the documentation.

=== Whitebox Overall System


_**<Overview Diagram>**_

Motivation::
The motivation of this diagram is to have a general vision of all different modules of the application.

Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Viade Client | It allows users to share routes and multimedia.
| Solid Server | It provides the PODs which store the information. 
|===

Important Interfaces::
Client-Server high level communication (HTTP).

=== Level 2

[role="arc42help"]
****
Here you can specify the inner structure of (some) building blocks from level 1 as white boxes.

You have to decide which building blocks of your system are important enough to justify such a detailed description.
Please prefer relevance over completeness. Specify important, surprising, risky, complex or volatile building blocks.
Leave out normal, simple, boring or standardized parts of your system
****

==== White Box _<building block 1>_

[role="arc42help"]
****
...describes the internal structure of _building block 1_.
****

_<white box template>_

==== White Box _<building block 2>_


_<white box template>_

...

==== White Box _<building block m>_


_<white box template>_



=== Level 3

[role="arc42help"]
****
Here you can specify the inner structure of (some) building blocks from level 2 as white boxes.

When you need more detailed levels of your architecture please copy this
part of arc42 for additional levels.
****


==== White Box <_building block x.1_>

[role="arc42help"]
****
Specifies the internal structure of _building block x.1_.
****


_<white box template>_


==== White Box <_building block x.2_>

_<white box template>_



==== White Box <_building block y.1_>

_<white box template>_
