[[section-building-block-view]]


== Building Block View
This section will show the static decomposition of the system into building blocks as well as their dependencies. We will zoom into black boxes of the different levels to show their components. 

For reference, we are going to use the scope and context diagram that has been described in the third section of the documentation.

=== Whitebox Overall System


_**<Overview Diagram>**_

Motivation::
The motivation of this diagram is to have a general vision of all different modules of the application.

Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Viade Client | It allows users to share routes and multimedia.
| Solid Server | It provides the PODs which store the information. 
|===

Important Interfaces::
Client-Server high level communication (HTTP).

=== Level 2

==== White Box Viade Client
Contained Building Blocks::
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Route Module | It manages the routes and multimedia that users can share.
| RDF Service | It transforms data to/from RDF format.
| Solid Adapter Service | Link between Viade and Solid Server.
|===

==== White Box Solid Server
Contained Building Blocks::
 * Authentication
 * Authorization
 * HTTP
 * LDP
 * Storage

For more indepth information relative to this blocks, click link:https://rubenverborgh.github.io/solid-server-architecture/solid-architecture-v1-2-0.pdf[here].

=== Level 3
==== White Box Route Module
[cols="1,3" options="header"]
|===
| **Name** | **Responsibility**
| Friend Service | User friends are managed.
| Route Service | It manages all actions relative to routes.
| Notification Service | When a user shares a route, it allows to publish and suscribe a notification.
| Media Service | It manages the processing of media.
|===
