[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>


* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
title Viade
header Sequence diagram v.0.1

actor USER
participant UI
actor OTHER_USER
participant OTHER_USER_UI
control AuthService
database SOLID
control DataService
database POD
database OTHER_USER_POD

== Authentication ==

USER -> UI: Set (user/password) + LOGIN
UI -> AuthService: Authentication Request
AuthService -> SOLID: Validate credentials

alt successful login
	SOLID -> AuthService: Correct user credentials
	AuthService --> UI: Load HomePage

else failure login
	SOLID -> AuthService: Invalid user credentials
	AuthService --> UI: Load LoginPage
	end

== Store route ==

USER -> UI: ADD ROUTE
UI -> DataService: AddRoute()
DataService -> POD: Store route

alt successful	
	POD -> DataService: Route added
	DataService --> UI: Successful notification

else failure
	POD -> DataService: Route could't be added
	DataService --> UI: Failure notification
	end

== View route map ==

USER -> UI: RENDER ROUTE
UI -> DataService: getRoute()
DataService -> POD: Get Route

alt successful	
	POD -> DataService: Route available
	DataService --> UI: Successful notification

else failure
	POD -> DataService: Route info could't be reached
	DataService --> UI: Failure notification
	end

== Share content ==

USER -> UI: SHARE CONTENT
UI -> DataService: shareContent(otherUser)
DataService -> POD: Get Content
DataService -> OTHER_USER_POD: Send Content

alt successful	
	POD -> DataService: Content sended
	DataService --> UI: Successful notification

else failure
	POD -> DataService: Content not sended
	DataService --> UI: Failure notification
	end



alt successful	
	OTHER_USER_POD -> DataService: Content received
	DataService --> OTHER_USER_UI: Successful notification

else failure
	OTHER_USER_POD -> DataService: Content not received
	DataService --> OTHER_USER_UI: Failure notification
	end

----
=== <Runtime Scenario 2>

=== ...

=== <Runtime Scenario n>
