[[section-design-decisions]]
== Design Decisions

In this section we will talk about the design decisions made to implement our routes application.

* For the project interface, we are going to use Bootstrap libraries along with Solid React components and PrimeReact.

* *Programming language*: we will use JavaScript together with ReactJS libraries, all using the Node.js framework.

* *Data storage*: the data storage will be done through POD's implementations and through use of RDF/Turtle.

* *CQRS*: Command Query Reponsibility Segregation is a pattern used to separate the logic between commands and queries.
** A clear read model with a list of queries and domain objects you can use.
** An isolation of each command inside a write model.

* *Object/Turtle*: All the information used by the application will be from the data model defined in section 8.1. Domain Model. We use the SolidAdapter, which acts as a mapper between the model objects and the objects that can be stored in the Solid POD. It could be the equivalent of an ORM when working with relational databases, in this case we call it Object Linked Data Mapping. Through contexts, we use ldflex proxy to map the model object and save the data in the POD in RDF format. Then, when we download the data from the POD we obtain a js object that, when the corresponding factory processes it, becomes a model object.

* *Testing*: we will use unit test to business logic (Jest) and Cucumber for aceptance tests.
