[[section-quality-scenarios]]
== Quality Requirements


[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree

[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.
****

=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

[cols=4*,options="header"]
|===
|Ref
|AQ
|Scenario 
|Priority


|1
|Efficiency
|A user can access any route in less than 10 seconds
|High, Medium

|2
|Reliability
|All those actions that you want to do on the routes (create, delete, etc.) must appear updated in the application and can be delayed at most 1 hour
|Medium, High

|3
|Availability
|Any route stored in the database must be visible by any user who has the privilege for at least 97% of the time throughout the year.
|Medium, Medium

|4
|Availability
|In case of error, the fault will be saved in the log. This error must be accessible by any professional who works in the maintenance of this application
|Medium, High

|5
|Maintainability
|If you have to modify, update or make any changes to the application, it must be easily added thanks to the clean and precise code structure
|Medium, Medium

|6
|Testability
|Everything that involves functionality in the application must be tested before offering the new service to customers.
|Low, Medium

|7
|Portability
|The application must be able to be used in mobile devices and others that have the ability to be used in the street.
|Medium, Medium

|8
|Availability
|In case of failure of the servers, these will be replaced by ones that work correctly within 48 hours
|Medium, High

|9
|Security
|The application must support any type of external attack that directly affects the application and the users that use it.
|Low, Low

|10
|Modifiability
|In case you want to modify some aspect of the application, it must be possible to do it without any problem.
|Medium, Medium
|===

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
